[tool.mypy]
packages = ["urt30t"]
strict = true
warn_unreachable = true

[tool.ruff]
target-version = "py311"
extend-exclude = [".*"]
select = [
    "A",  # shadowing builtins
    "ARG",  # unused arguments
    "ASYNC",  # async checks
    "B",  # bugbear
    "C4",  # comprehensions
    "DTZ",  # checks for naive datetimes
    "E",  # pycodestyle (errors)
    "ERA",  # eradicate (commented out code)
    "F",  # Pyflakes
    "FBT",  # boolean trap
    "I",   # isort
    "ISC",  # Implicit String Concat
    "N",  # pep8-naming
    "PIE",  # misc lints
    "PL",  # Pylint
    "PT",  # Pytest
    "PTH",  # favor pahtlib.Path
    "RET",  # returns
    "RUF",  # Ruff-specific rules
    "S",  # bandit
    "SIM",  # simplify
    "T20",  # print statements
    "TRY",  # tryceratops
    "UP",  # pyupgrade
    "W",  # pycodestyle (warnings)
]
ignore = ["ISC001"]

[tool.ruff.per-file-ignores]
"alembic/env.py" = ["I001", "ERA001"]
"urt30t/events.py" = ["S101"]
"tests/**.py" = ["PLR2004", "S101"]

[tool.ruff.flake8-builtins]
builtins-ignorelist = ["id", "type"]

[tool.ruff.pep8-naming]
classmethod-decorators = ["pydantic.field_validator"]

[tool.ruff.pylint]
max-args = 8

[tool.ruff.format]
preview = true
