[bot]
name = "30+Bot"

# prefix for all chat messages sent by the bot
message_prefix = "^0(^230+Bot^0)^7:"

# date format used by the bot
# see https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes
time_format = "%I:%M%p %Z %m/%d/%y"

# IANA time zone database format
# see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
time_zone_name = "UTC"

# full path to the `games.log` file
games_log = "~/server/q3ut4/games.log"

# SQLAlchemy url, ex. sqlite+aiosqlite:///file_path
db_url = "sqlite+aiosqlite:///~/.config/urt30t.sqlite"

# if set to true, extra logging of issued DML statements will be output
db_debug = false

# maximum backlog of events to store, if more events come in
# they will be discarded
event_queue_max_size = 100

# prefix to use for issuing bot commands from chat
# for example, $balance
command_prefix = "!"

# list of plugins to enable on startup
plugins = []

# delay between reading lines from the games.log
log_read_delay = 0.250

# if you rotote the games.log, then enable this setting
log_check_truncated = false

# if enabled will read all events in the games.log, the default
# setting is to only read new lines
log_replay_from_start = false

[rcon]
host = "127.0.0.1"
port = 27960
password = ""
recv_timeout = 0.25

[log_levels]
root = "WARNING"
core = "INFO"
rcon = "INFO"
plugins = "INFO"
